### PR TITLE
Fix release-scope build lifecycle hook

### LINKED ISSUE #935: Lifecycle hook doesn't work at release scope
**Describe the bug**

**General info (please complete the following information):**

- OS: macOS
- Helmwave Version 0.38.0

**To Reproduce**

**Expected behavior**
https://docs.helmwave.app/0.38.x/examples/lifecycle/ 

**Screenshots / Stdout**
If applicable, add screenshots / stdout logs to help explain your problem

### PR DESCRIPTION
**Pull request by Vigilans**
Closes #935 

Actually there are pre/post-up/down/rollback code for release-scope lifecycle hooks, only build hook is missing.

### CODE REVIEW

**Comment by zhilyaev** [comment]
@Vigilans Thank you for your contributions!
We use [changie](https://changie.dev/) to provide changes for users. Could you add a changie note with your PR?

I have switched the base from main to release/0.39.0

**Comment by Vigilans** [comment]
@zhilyaev I've added the changie commit.

File: pkg/plan/build_releases.go [hunk 1]
```diff
@@ -45,15 +47,33 @@ func addToPlan(
...
+
+	defer func() {
+		lifecycleErr := lifeCycle.RunPostBuild(ctx)
+		if lifecycleErr != nil {
+			log.Errorf("got an error from postbuild hooks: %v", lifecycleErr)
+			if err == nil {
+				err = lifecycleErr
+			}
+		}
+	}()
```
Comment (r3nic1e) [inline pkg/plan/build_releases.go:65]: I am not sure this is the place both of these lifecycles should be run.

IMO:

- per-release pre-build should be run after `p.buildReleases(o.Tags, o.MatchAll)` (so as soon as we know list of releases, we run the hook)
- per-release post-build should be run in the end of `*Plan.Build` (after everything was built)

Comment (Vigilans) [reply pkg/plan/build_releases.go:65]: `addToPlan` happens during `p.buildReleases`, and will make pre-build hook to be executed in _dependency order_. 

But after you mentioned I found that releases in `plan` are already in dependency order. So indeed it can be run after `p.buildReleases`.

Comment (Vigilans) [reply pkg/plan/build_releases.go]: @r3nic1e  I've altered the hook point according to your comment.

File: pkg/plan/build.go [hunk 2]
```diff
@@ -40,6 +40,18 @@ func (p *Plan) Build(ctx context.Context, o BuildOptions) (err error) {
 			if err == nil {
 				err = lifecycleErr
 			}
+			return
+		}
+		for _, r := range p.body.Releases {
```
Comment (r3nic1e) [inline pkg/plan/build.go:45]: I think it should be run before global post-build hook

**Review by r3nic1e — APPROVED** [review]
I will merge it a bit later. Sorry for long review
