### PR TITLE
fix: kubedog missing config

### LINKED ISSUE #236: Kubedog missing kubeconfig
`export KUBECONFIG="/workdir/config"`

### PR DESCRIPTION
**Pull request by r-mironov**
close #236

### CODE REVIEW

File: pkg/plan/apply.go [hunk 1]
```diff
@@ -205,11 +207,27 @@ func (p *Plan) syncReleasesKubedog(kubedogConfig *kubedog.Config) error {
...
+		kube.Kubernetes = clientset
+		kube.Client = clientset
+
+		dynamicClient, err := dynamic.NewForConfig(config)
+		if err != nil {
+			return fmt.Errorf("failed to initialize kubernetes config: %w", err)
+		}
+		kube.DynamicClient = dynamicClient
+	}
+
```
Comment (r3nic1e) [inline pkg/plan/apply.go:230]: lets move this to separate function (probably in pkg/helper)

**Review by r3nic1e — CHANGES_REQUESTED** [review]

File: pkg/plan/apply.go (hunk 1 above)
Comment (r-mironov) [reply pkg/plan/apply.go]: done

File: pkg/helper/kubedog.go [hunk 2]
```diff
@@ -0,0 +1,23 @@
+package helper
+
+import (
+	"fmt"
+	"os"
+
+	"github.com/werf/kubedog/pkg/kube"
+)
+
+func KubeInit() error {
```
Comment (r3nic1e) [inline pkg/helper/kubedog.go:10]: exported function KubeInit should have comment or be unexported

**Review by r3nic1e — CHANGES_REQUESTED** [review]

**Review by r3nic1e — APPROVED** [review]
